[package]
name = "clarity"
version = "0.5.1"
authors = ["Michał Papierski <michal@papierski.net>, Justin Kilpatrick <justin@althea.net>"]
autotests = true
include = [
    "**/*.rs",
    "Cargo.toml"
]
description = "Lightweight Ethereum client"
repository = "https://github.com/althea-net/clarity"
license-file = "LICENSE"
edition = "2021"

[badges]
travis-ci = { repository = "althea-net/clarity", branch = "master" }

[dependencies]
secp256k1 = { version = "0.24", features = ["recovery"] }
serde = "1.0"
serde-rlp = { git = "https://github.com/onomyprotocol/serde-rlp.git", rev = "37871c8b27608319a9ed4d1872d38fe28dc1872a" }
serde_bytes = "0.11"
serde_derive = "1.0"
sha3 = "0.10"
u64_array_bigints = { version = "0.3", default-features = false }

[dev-dependencies]
criterion = "0.3"
rand = "0.8"
serde_json = "1.0"

[[bench]]
name = "crypto_bench"
harness = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
